const STARS = [
  `<span class="far">star</span>
  <span class="far">star</span>
  <span class="far">star</span>
  <span class="far">star</span>
  <span class="far">star</span>`,
  `<span class="fas">star</span>
  <span class="far">star</span>
  <span class="far">star</span>
  <span class="far">star</span>
  <span class="far">star</span>`,
  `<span class="fas">star</span>
  <span class="fas">star</span>
  <span class="far">star</span>
  <span class="far">star</span>
  <span class="far">star</span>`,
  `<span class="fas">star</span>
  <span class="fas">star</span>
  <span class="fas">star</span>
  <span class="far">star</span>
  <span class="far">star</span>`,
  `<span class="fas">star</span>
  <span class="fas">star</span>
  <span class="fas">star</span>
  <span class="fas">star</span>
  <span class="far">star</span>`,
  `<span class="fas">star</span>
  <span class="fas">star</span>
  <span class="fas">star</span>
  <span class="fas">star</span>
  <span class="fas">star</span>`,
];
export default STARS;
